# mkdocs.yml

site_name: py-llm-shield # <-- ATUALIZADO
site_description: "Validação e estruturação de saídas de LLMs com a simplicidade do Pydantic."
site_author: "Giovanni Lemos Barcelos" # <-- ATUALIZADO

# Nota: O nome do repositório no GitHub pode continuar sendo 'llm-guard'.
# Se você decidir renomeá-lo no GitHub, atualize a URL aqui.
repo_url: https://github.com/thirteeng/llm-guard
repo_name: thirteeng/llm-guard

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.top

nav:
  - 'Home': 'index.md'
  - 'Instalação': 'installation.md'
  - 'Guia de Início Rápido': 'quickstart.md'